### ISSUE TITLE
请问有建表的sql吗

### ISSUE THREAD

**Issue by l312770312** [cckevincyh/CompanyWebsite#1]
在项目中没有找到数据库语句，希望能帮帮忙，谢谢你

**Comment by cckevincyh** [comment]
你在mysql创建一个数据库creat database  CompanyWebsite。之后开启tomcat即可。

**Comment by wdengf** [comment]
你在mysql创建一个数据库creat database CompanyWebsite。之后开启tomcat即可。

创建了CompanyWebsite数据库，那表不能自动生成。如果可以的话，能不能发一份sql，非常感谢

**Comment by cckevincyh** [comment]
@UntilHell 已新增sql文件
