### ISSUE TITLE
网站运行后404

### ISSUE THREAD

**Issue by wx0322** [cckevincyh/CompanyWebsite#5]
The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.

运行环境是tomcat8 + jdk1.8 + mysql5.7 + eclipse
请问是不是还需要安装什么其他插件呢？
jdk和tomcat的环境变量都配置了。

**Comment by cckevincyh** [comment]
@wx0322 有错误提示吗？你可以参考下：https://github.com/cckevincyh/OnLineTest/issues/4. 尝试解决一下。
